server {
    # 80번 포트에서 HTTP 요청을 수신
    listen 80;
    # 서버 이름을 localhost로 설정
    server_name localhost;

    # 모든 요청 처리
    location / {
        root /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }

    # 백엔드 api 요청에 대한 Proxy 설정 (k8s ingress와 동일한 경로 규칙 적용)
    location /boot/ {
        proxy_pass http://backend-app-svc:8080/;
    }
}